### ISSUE TITLE
What's the meaning of the attributes in the result json file?

### ISSUE THREAD

**Issue by Kevin6liu6** [nv-tlabs/STRIVE#2]
I was able to generate adversarial scenarios following the instructions, and got several BEV images/videos along with a json file. I printed the keys and got ['N', 'dt', 'map', 'lw', 'sem', 'past', 'fut_init', 'fut_adv', 'fut_internal_ego', 'fut_sol', 'attack_agt', 'attack_t', 'z_adv', 'z_sol', 'z_prior']. I am wondering what are the meanings of these keys.

**Comment by davrempe** [comment]
What you probably care most about is `past` and `fut_adv` which are the past trajectories and future trajectories for all agents in the final adversarial scenario. 

A full explanation of all fields is as follows:
* `N`- the number of agents
* `dt` - timestep size of scenario
* `map` - name of the map in the dataset that this scenario is on
* `lw` - the length and width of the bounding boxes for each agent
* `sem` - the semantic category of each agent indicated by a one-hot vector
* `past` - the past trajectories of agents in the scene
* `fut_init` - the future trajectories of agents used to _initialize_ the optimization
* `fut_adv` - the future trajectories of agents in the final adversarial scenario (i.e. the output of the adversarial optimization)
* `fut_internal_ego` - this is our method's prediction of the ego agent trajectory after adversarial optimization
* `fut_sol`- the solution trajectory for the ego to avoid the adversarial attack (i.e. the output of the solution optimization)
* `attack_agt` - the index of the "attacking" agent, i.e. the one that causes the collision or gets closest
* `attack_t` - the timestep of the attack (collision) or the timestep that's closest to a collision
* `z_adv` - the VAE latent vector for the final adversarial scenario
* `z_sol` - the VAE latent vector for the final solution scenario
* `z_prior` - the mean and variance of the latent distribution output by the encoder of our model

The [evaluation script](https://github.com/nv-tlabs/STRIVE/blob/5454655545e4754a4ea3dbe35b1f36d3d94747f5/src/eval_adv_gen.py#L74) shows how to read in these json files and visualize them.

**Comment by yang-yang-wei** [comment]
Is it possible to use STRIVE to generate adversarial scenes on datasets other than nuscenes, and if so, what to do
